apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-sci-ops-setup-validator-backend.fullname" . }}
  labels:
    {{- include "ska-sci-ops-setup-validator-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ska-sci-ops-setup-validator-backend.selectorLabels" . | nindent 4 }}
